name: test_moor_order

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor: ^4.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^1.0.0
  moor_generator: ^4.5.0
  build_runner: ^2.1.1

flutter:
  uses-material-design: true
